spring:
  application:
    name: shopdev
  datasource:
    url: jdbc:mysql://localhost:3306/shopdev
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        useSSL: false
